### ISSUE TITLE
manifest locales

### ISSUE THREAD

**Issue by hspencer** [accesibilidad-inclusion/pictogramas#17]
@felipelavinz o @basilio no entendimos por qué ambos `manifest.json` (en, es) están en inglés. ¿Alguna ocnsideración para los nuevos updates?

**Comment by basilio** [comment]
@hspencer las etiquetas están en inglés porque no tienen nombres asignados. Copiamos el nombre del archivo dentro de la propiedad `label` sólo para que se vea en pantalla. El trabajo que deben hacer es renombrar esa propiedad de cada pictograma, con el nombre que tendrá en el idioma que corresponda.

![imagen](https://user-images.githubusercontent.com/155106/96741064-d1749500-1397-11eb-847b-631891ca96bc.png)
