### ISSUE TITLE
Mejoras de organización del repositorio

### ISSUE THREAD

**Issue by felipelavinz** [accesibilidad-inclusion/pictogramas#20]
Hola @hspencer 

Actualmente hay varias ramas activas en el repositorio, en especial "master" y "gh-pages"; esta última se está utilizando fundamentalmente para construir la visualización web que está en https://accesibilidad-inclusion.github.io/pictogramas/

Propongo integrar gh-pages a master y construir la visualización web directamente desde master, de modo de reducir la complejidad de administración del repo.

Adicionalmente, al hacer el merge podemos usar la opción "squash commits" para integrar todos los cambios en un solo commit y asi evitar "inflar" el peso del repositorio con los archivos binarios que en algún punto estaban versionados.

Con respecto a los archivos de Illustrator, identifico básicamente tres opciones: 

1. Utilizar ["Large file storage"](https://github.blog/2015-04-08-announcing-git-large-file-storage-lfs/) - al parecer se podría integrar de forma transparente en el repositorio, pero tiene un límite gratuito bastante limitado. Se puede pagar para elevar ese límite.
2. Incorporarlos como otro repositorio, que podría estar hosteado en el servidor de la e[ad] - sería más complejo de administrar, pero podríamos tener más control en cuanto al uso de espacio. También sería más complejo manejar los aportes a los archivos Illustrator.
3. Dejar de utilizar archivos de Illustrator y en su lugar usar únicamente SVG. Esto sería por lejos la mejor opción en cuanto a facilidad de integrar en el repo, incluir nuevas contribuciones, etc.

Espero tus comentarios,
saludos!

**Comment by hspencer** [comment]
Gracias @felipelavinz, me parece apropiado hacer un squash y sacar los originales a otro repositorio. ¿Es posible dejar un repositorio dentro de otro? (referenciado, al menos)

**Comment by felipelavinz** [comment]
Sí @hspencer hay (al menos) dos formas:

- una es a través de [submódulos de git](https://git-scm.com/book/en/v2/Git-Tools-Submodules), que es una característica propia de git, pero tiene varios problemas en particular con la incorporación de cambios
- otra opción es hacerlo a través de npm/yarn, definiendo el repo de orginales como una **dependencia opcional** o como **dependencia de desarrollo**. En ambos casos, la dependencia puede ser otro repositorio git o bien una URL a un archivo .tar.gz

Me parece que la segunda opción es más conveniente. Inicialmente podría ser otro repo de github y podemos ir monitoreando cómo funciona.

slds!

**Comment by hspencer** [comment]
@felipelavinz entonces, para organizarnos:

1. cualquier actualización a `master` actualizará PICTOS producción
2. cualquier actualización a `qa` actualizará PICTOS QA (que debiese ser el paso 1 para cualquier release, osea, probamos en  `qa` y pasamos a `master` una vez revisado todo )
3. `gh-pages` será el branch para el sitio / herramienta online. `master`y `qa`estarán optimizados y no tendrán archivos extras
4. vamos a hacer otro repo `pictogramas-src`donde estarán los archivos editables y cualquier otra documentación no escencial al deployment.

**Comment by felipelavinz** [comment]
Hola @hspencer 

te comento por punto:

1. Sí, correcto
2. Eso no está contemplado en los cambios que están implementados actualmente. Para que eso funcione de ese modo es necesario programar una integración con una acción de github; podemos probar si tiene una resolución rápida para contemplarlo como parte de esta misma tarea pero si se extiende creo que se debiera considerar como una nueva tarea.
3. No, `master` es la rama principal y desde la cual se construye el sitio, no se debe mantener una rama separada para el sitio. Ninguna rama debiese tener archivos extra — si eso fuera necesario se debiese hacer a través de forks que se trabajan de forma individual y luego se integran en estado listo para producción y se cierran.
4. Ok, pero resolvamos posteriormente en una nueva tarea cómo se vinculan ambos repositorios. Lo ideal sería trabajar todo en formatos que se guarden como texto plano (independiente del programa que usen para trabajarlos), ya que es como mejor opera git

saludos!
