### ISSUE TITLE
Relase nueva versión de pictogramas

### ISSUE THREAD

**Issue by felipelavinz** [accesibilidad-inclusion/pictogramas#25]
Hola @reneerodo @hspencer 

para completar el paso a producción de los nuevos pictogramas, necesitamos su ayuda con:

- [x]  Validar los nuevos pictogramas; pueden utilizar la herramienta online para probar en: https://accesibilidad-inclusion.github.io/pictogramas/ (estamos en proceso de migración a pictogramas.pictos.cl). Ya están aplicados también en el admin QA.
- [x] Completar la información de los nuevos pictogramas en el archivo manifest.json; para eso deben complementar el archivo que está actualmente en la rama QA: https://github.com/accesibilidad-inclusion/pictogramas/blob/qa/public/es/manifest.json (los nuevos pictos tienen "label" vacío)
- [x] Completar la versión traducida del archivo manifest.json a inglés

cc @antopasten @jacodiego @pedroarellano

**Comment by reneerodo** [comment]
Hola Felipe, perfecto, avanzaré con esas tareas.
muchas gracias

**Comment by reneerodo** [comment]
Hola @felipelavinz 
Aquí hice los cambios del .json 
https://github.com/accesibilidad-inclusion/pictogramas/commit/759a3ce8e95342c1b690d7f381b6e0f62163d5f0

**Comment by reneerodo** [comment]
@felipelavinz te quería pedir si me puedes dejar el link para modificar el .json en inglés
Muchas gracias!

**Comment by felipelavinz** [comment]
Hola @reneerodo puede ser a partir de este link:

https://github.com/accesibilidad-inclusion/pictogramas/blob/v2/public/en/manifest.json

saludos!

**Comment by reneerodo** [comment]
listo @felipelavinz : 
https://github.com/accesibilidad-inclusion/pictogramas/compare/v2...reneerodo-patch-2-1?quick_pull=1
